// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCinDHgC0emxsjHKVRDqBGo7M2i65da48I',
    appId: '1:576736049563:web:f6c70d0fb87e505966093e',
    messagingSenderId: '576736049563',
    projectId: 'simple-cbfcb',
    authDomain: 'simple-cbfcb.firebaseapp.com',
    storageBucket: 'simple-cbfcb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO9VKPn_x97o4SNAzw0lHpX6yDj3SFdkI',
    appId: '1:576736049563:android:991672427891563566093e',
    messagingSenderId: '576736049563',
    projectId: 'simple-cbfcb',
    storageBucket: 'simple-cbfcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrR5q6nuFvHEfyPFat-kO5J3La-J-rd48',
    appId: '1:576736049563:ios:900f5fc4fbdf2ec366093e',
    messagingSenderId: '576736049563',
    projectId: 'simple-cbfcb',
    storageBucket: 'simple-cbfcb.appspot.com',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrR5q6nuFvHEfyPFat-kO5J3La-J-rd48',
    appId: '1:576736049563:ios:cc22166bd8d3a78b66093e',
    messagingSenderId: '576736049563',
    projectId: 'simple-cbfcb',
    storageBucket: 'simple-cbfcb.appspot.com',
    iosBundleId: 'com.example.student.RunnerTests',
  );
}
